---
- hosts: localhost
  gather_facts: no
  vars:
    image_id: "ami-09d95fab7fff3776c"
  module_defaults: 
    group/aws:
      region: "us-east-1"
  tasks:
    - name: Create Launch Template
      ec2_launch_template:
        name: "M5_launch_template"
        image_id: "{{ vpc.vpc.id }}"
        key_name: Launch
        instance_type: t3.nano
        version: 1
        iam_instance_profile: "image-gallery-server-role"
        security_group_ids:
        network_interfaces:
         - device_index: 0
           groups: ["{{ M5_postgres_tag.group_id }}","{{ M5_default_sg.group_id }}","{{ M5_developer_sg.group_id }}"]
           associate_public_ip_address: yes
           subnet_id: "{{ public_subnet.subnet.id }}"
        user_data: "{{ lookup('file', './ec2-scripts/ec2-prod-1.1.sh') | b64encode }}"
        state: present
      register: M5_lt
    - name: Create Target Group
      elb_target_group:
        name: M5-target-group
        protocol: tcp
        port: 80
        vpc_id: "{{ vpc.vpc.id }}"
        state: present
        target_type: instance
        stickiness_enabled: no
        stickiness_type:
      register: M5_target_group
    - name: Grab EIP for NLB Subnet
      ec2_eip_info:
        filters:
            tag:Name: M5-nginx-load-balancer-1
      register: eip
    - name: debug
      debug: var=eip
    - name: Create Network Load Balancer
      elb_network_lb:
        name: M5-load-balancer
        subnet_mappings:
          - SubnetId: "{{ public_subnet.subnet.id }}"
            AllocationId: "{{ eip.addresses[0].allocation_id }}"
          - SubnetId: "{{ public_subnet2.subnet.id }}"
        listeners:
          - Protocol: TLS
            Certificates:
              - CertificateArn: "arn:aws:acm:us-east-1:035118526046:certificate/db76529f-5b54-482b-aa8c-482e9c30bea9"
            Port: 443
            DefaultActions:
              - Type: forward
                TargetGroupName: M5-target-group
        tags:
          Name: M5-load-balancer
        state: present
    - name: Create Auto Scaling Group
      ec2_asg:
        name: M5-asg
        availability_zones: ["us-east-1b", "us-east-1d"]
        launch_template:
          launch_template_name: "{{ M5_lt.template.launch_template_name }}"
          launch_template_id: "{{ M5_lt.template.launch_template_id }}"
        min_size: 2
        max_size: 4
        desired_capacity: 2
        target_group_arns: "{{ M5_target_group.target_group_arn }}"
        vpc_zone_identifier: ["{{ public_subnet.subnet.id }}", "{{ public_subnet2.subnet.id }}"]



