---
- hosts: localhost
  gather_facts: no
  module_defaults: 
    group/aws:
      region: "us-east-1"
      zone: "us-east-1b"
  tasks:
    - name: Provision Staging EC2 Instance
      ec2:
        key_name: Launch
        instance_type: t3.nano
        instance_tags:
          Name: M5_dev
          exact_count: 1
          count_tag:
             Name: M5_dev
        instance_profile_name: "image-gallery-server-role"
        wait: yes
        image: "ami-09d95fab7fff3776c"
        vpc_subnet_id: "{{ public_subnet2.subnet.id }}"
        group_id: ["{{ M5_postgres_tag.group_id }}","{{ M5_default_sg.group_id }}","{{ M5_developer_sg.group_id }}"]
        assign_public_ip: yes
      register: ec2_dev
    - name: debug
      debug: var=ec2_dev
    - name: Add ec2 to inventory
      add_host:
        name: "{{ ec2_dev.instances[0].public_ip }}"
        groups: bastion
        rds_address: "{{ rds.instance.endpoint }}"
