---
- hosts: localhost
  gather_facts: no
  vars:
    image_id: "ami-09d95fab7fff3776c"
    script: |
      #!/usr/bin/bash

      export IMAGE_GALLERY_BOOTSTRAP_VERSION="1.0"

      aws s3 cp s3://eli.samek.image-gallery.config/ec2-prod-latest.sh ./
      /usr/bin/bash ec2-prod-latest.sh
  module_defaults: 
    group/aws:
      region: "us-east-1"
  tasks:
    - name: Create Launch Template
      ec2_launch_template:
        name: "M5_launch_template"
        image_id: "ami-09d95fab7fff3776c"
        key_name: Launch
        instance_type: t3.nano
        iam_instance_profile: "image-gallery-server-role"
        network_interfaces:
         - device_index: 0
           groups: ["{{ M5_postgres_tag.group_id }}","{{ M5_default_sg.group_id }}","{{ M5_developer_sg.group_id }}"]
           associate_public_ip_address: yes
           subnet_id: "{{ public_subnet.subnet.id }}"
        user_data: "{{ script | b64encode }}"
        state: present
      register: M5_lt
    - name: Create Target Group
      elb_target_group:
        name: M5-target-group
        protocol: tcp
        port: 80
        vpc_id: "{{ vpc.vpc.id }}"
        state: present
        target_type: instance
        stickiness_enabled: no
        stickiness_type:
      register: M5_target_group
    - name: Grab EIP for NLB Subnet
      ec2_eip_info:
        filters:
            tag:Name: M5-nginx-load-balancer-1
      register: eip
    - name: debug
      debug: var=eip
    - name: Create Network Load Balancer
      elb_network_lb:
        name: M5-load-balancer
        subnet_mappings:
          - SubnetId: "{{ public_subnet.subnet.id }}"
            AllocationId: "{{ eip.addresses[0].allocation_id }}"
          - SubnetId: "{{ public_subnet2.subnet.id }}"
        listeners:
          - Protocol: TLS
            Certificates:
              - CertificateArn: "arn:aws:acm:us-east-1:035118526046:certificate/db76529f-5b54-482b-aa8c-482e9c30bea9"
            Port: 443
            DefaultActions:
              - Type: forward
                TargetGroupName: M5-target-group
          - Protocol: TCP
            #Certificates:
             # - CertificateArn: "arn:aws:acm:us-east-1:035118526046:certificate/db76529f-5b54-482b-aa8c-482e9c30bea9"
            Port: 80
            DefaultActions:
              - Type: forward
                TargetGroupName: M5-target-group
        tags:
          Name: M5-load-balancer
        state: present
      register: M5_lb
    - name: Create Auto Scaling Group
      ec2_asg:
        name: M5-asg
        availability_zones: ["us-east-1b", "us-east-1d"]
        launch_template:
          launch_template_name: "{{ M5_lt.template.launch_template_name }}"
          launch_template_id: "{{ M5_lt.template.launch_template_id }}"
        min_size: 2
        max_size: 4
        desired_capacity: 2
        target_group_arns:
          - "{{ M5_target_group.target_group_arn }}"
        vpc_zone_identifier: ["{{ public_subnet.subnet.id }}", "{{ public_subnet2.subnet.id }}"]
        health_check_type: EC2
        health_check_period: 300
        state: present
    - name: Update Route53 record with alias to ELB
      route53:
        state: present
        zone: elisamek.codes
        record: www.elisamek.codes
        identifier: elisamek.codes
        type: A
        region: us-east-1
        value: "{{ M5_lb.dns_name }}"
        alias: True
        alias_hosted_zone_id: "{{ M5_lb.canonical_hosted_zone_id }}"
        overwrite: yes
    - name: Update Route53 record with alias to ELB
      route53:
        state: present
        zone: elisamek.codes
        record: elisamek.codes
        identifier: elisamek.codes
        region: us-east-1
        type: A
        value: "{{ M5_lb.dns_name }}"
        alias: True
        alias_hosted_zone_id: "{{ M5_lb.canonical_hosted_zone_id }}"
        overwrite: yes
    - name: Add A record to Route53
      route53:
        state: present
        zone: elisamek.codes
        record: elisamek.codes
        identifier: elisamek.codes
        region: us-east-1
        type: A
        ttl: 7200
        value: "{{ eip.addresses[0].public_ip }}"
        wait: yes
        overwrite: yes
    - name: Add A record to Route53 "www"
      route53:
        state: present
        zone: elisamek.codes
        record: www.elisamek.codes
        identifier: elisamek.codes
        region: us-east-1
        type: A
        ttl: 7200
        value: "{{ eip.addresses[0].public_ip }}"
        wait: yes
        overwrite: yes




