---
- hosts: all
  become: yes
  tasks:
    - name: install nano
      package:
         name: nano
         state: present
    - name: install apache
      package: name=httpd state=present
    - name: start apache
      service:
        name: httpd
        state: started
        enabled: true
